# Generated by Django 6.0.6 on 2026-06-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_by',
            new_name='created_by',
        ),
    ]
